//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efficient.Json {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Efficient.Json.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of type &apos;{0}&apos;.
        /// </summary>
        internal static string Convert_CreateFailed {
            get {
                return ResourceManager.GetString("Convert.CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected name &apos;{0}&apos; on type &apos;{1}&apos;.
        /// </summary>
        internal static string Convert_InvalidMember {
            get {
                return ResourceManager.GetString("Convert.InvalidMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a string key from token type {0}.
        /// </summary>
        internal static string Convert_KeyStringFailed {
            get {
                return ResourceManager.GetString("Convert.KeyStringFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; on type &apos;{1}&apos; has no setter.
        /// </summary>
        internal static string Convert_NoSetter {
            get {
                return ResourceManager.GetString("Convert.NoSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert value &apos;{0}&apos; to type &apos;{1}&apos;.
        /// </summary>
        internal static string Convert_TypeFailed {
            get {
                return ResourceManager.GetString("Convert.TypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected comma or close bracket after array.
        /// </summary>
        internal static string Parser_ExpectedCommaOrBracket {
            get {
                return ResourceManager.GetString("Parser.ExpectedCommaOrBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected comma or close curly brace after value.
        /// </summary>
        internal static string Parser_ExpectedCommaOrCurly {
            get {
                return ResourceManager.GetString("Parser.ExpectedCommaOrCurly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a colon after the key name.
        /// </summary>
        internal static string Parser_ExpectedKeyColon {
            get {
                return ResourceManager.GetString("Parser.ExpectedKeyColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a string key name.
        /// </summary>
        internal static string Parser_ExpectedKeyName {
            get {
                return ResourceManager.GetString("Parser.ExpectedKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a value.
        /// </summary>
        internal static string Parser_ExpectedValue {
            get {
                return ResourceManager.GetString("Parser.ExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string.
        /// </summary>
        internal static string Parser_InvalidStringToken {
            get {
                return ResourceManager.GetString("Parser.InvalidStringToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error at line &apos;{0}&apos; column &apos;{1}&apos;. Text: &apos;{2}&apos; Path: &apos;{3}&apos;. {4}..
        /// </summary>
        internal static string Parser_Message {
            get {
                return ResourceManager.GetString("Parser.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not expecting a value.
        /// </summary>
        internal static string Parser_UnexpectedValue {
            get {
                return ResourceManager.GetString("Parser.UnexpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Path support is not implemented.
        /// </summary>
        internal static string Query_NotImplemented {
            get {
                return ResourceManager.GetString("Query.NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse number &apos;{0}&apos;.
        /// </summary>
        internal static string Value_BadNumber {
            get {
                return ResourceManager.GetString("Value.BadNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value&apos;s type is &apos;{0}&apos; instead of &apos;{1}&apos;.
        /// </summary>
        internal static string Value_WrongType {
            get {
                return ResourceManager.GetString("Value.WrongType", resourceCulture);
            }
        }
    }
}
